language: php

php:
  - 7.1
  - 7.2

sudo: false

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source --optimize-autoloader

script: vendor/bin/phpunit --verbose
